# Generated by Django 6.1.1 on 2026-09-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('basic', 'Python基礎'), ('cert', 'Python3認定基礎試験対策')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', '初級'), ('normal', '中級'), ('hard', '上級')], max_length=20)),
                ('question', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
