# Generated by Django 6.1.1 on 2026-09-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('select', '4択クイズ'), ('code', 'コード作成クイズ')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('basic', 'Python基礎'), ('cert', 'Python3認定基礎試験対策')], max_length=20, null=True)),
                ('difficulty', models.CharField(choices=[('easy', '初級'), ('normal', '中級'), ('hard', '上級')], max_length=20)),
                ('score', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('accuracy', models.FloatField()),
                ('rank', models.CharField(blank=True, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
