# Generated by Django 6.1.1 on 2026-09-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('select', '4択クイズ'), ('code', 'コード作成クイズ')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', '初級'), ('normal', '中級'), ('hard', '上級')], max_length=20)),
                ('score', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('accuracy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
