# Generated by Django 6.1.1 on 2026-09-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizhistory_delete_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='rank',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
