# Generated by Django 6.1.1 on 2026-09-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizhistory_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
