# Generated by Django 6.1.1 on 2026-09-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', '初級'), ('normal', '中級'), ('hard', '上級')], max_length=20)),
                ('question', models.TextField()),
                ('explanation', models.TextField()),
                ('rules', models.JSONField()),
            ],
        ),
    ]
